vim.opt_local.foldlevel = 2
vim.opt_local.foldmethod = "expr"
vim.opt_local.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt_local.linebreak = false
vim.opt_local.spell = true
vim.opt_local.wrap = true
vim.opt_local.formatexpr = ""
vim.opt_local.conceallevel = 1
-- vim.opt_local.concealcursor = "nc"
-- vim.g.markdown_folding = 1
