alias cm="chezmoi"
alias cma="cm edit --apply"
alias zedit="cma ~/.zshrc"
alias vedit="cma ~/.config/nvim/init.vim"
alias tedit="cma ~/.config/tmux/tmux.conf"
alias aedit="cma ~/.local/share/zsh/aliases/090_general.zsh"
